### ISSUE TITLE
How to turn on the REST API?

### ISSUE THREAD

**Issue by boatmisser** [ibm-messaging/mq-docker#74] opened 2017-06-08 02:21 UTC
This is probably a stupid question and I apologise for that but I cannot for the life of me find out how to turn on the REST API when running MQ in a docker container.
The console web application works fine out of the box, but when I try to use the REST API I just get 404.
Normally you are supposed to to add `<variable name="mqRestAutostart" value="true" />` to `mqwebuser.xml`; but I can't find any documentation on how to get the REST API started during a docker run.

**Comment by parrobe** [comment] 2017-06-08 09:28
Hi @boatmisser. It's not a stupid question so don't worry.

Reading the MQ doc i can see that you're correct that to start the REST API for 9.0.1 you have to add `<variable name="mqRestAutostart" value="true" />` to `mqwebuser.xml`. Unfortunately there is no mechanism in our container image  currently to inject that statement and enable the REST API. Alternatively in 9.0.2+ the REST API is enabled by default.

I'll take this on as a defect and look into getting the REST API enabled by default using one of the two methods above.

**Comment by parrobe** [comment] 2017-06-08 10:23
Hi @boatmisser - We've just merged a Pull Request that should fix this issue. Could you ensure you have the latest master/release (v3.0) and try to recreate the problem.

**Comment by parrobe** [comment] 2017-08-24 12:31
Hi Boatmisser, REST API has been enabled and Basic HTTP Authentication has also been setup with the same credentials you use to log in to the Console with.

As it's been several months since you've responded on this issue i'll be closing it. If you get a chance to take a look and the problem is still there then please re-open this issue.

**Closed by parrobe** 2017-08-24 12:31 UTC
Labels: bug, enhancement
